name: My-React-App

on:
  [workflow_dispatch]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: checkout code 
            uses: actions/checkout@v3

          - name: Podman build image
            run: podman build -t my-react-app:latest .

          - name: Docker push image
            run: echo "testing"
              # docker login -u denzoenzo916 -p ${{ secrets.DOCKER_HUB_TOKEN }}
              # docker tag my-react-app denzoenzo916/my-react-app:v1.0
              # docker push denzoenzo916/my-react-app:v1.0
          
          - name: Install OpenShift CLI
            uses: redhat-actions/openshift-tools-installer@v1
            with:
              oc: "4"
              
          - name: Login to Openshift
            uses: redhat-actions/oc-login@v1
            with:
              openshift_server_url: ${{ secrets.OPENSHIFT_URL }}
              openshift_token: ${{ secrets.OPENSHIFT_TOKEN}}





            
