name: My-React-App

on:
  push
  #workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: checkout code 
            uses: actions/checkout@v3

          - name: Install OpenShift CLI
            uses: redhat-actions/openshift-tools-installer@v1
            with:
              oc: "4"
              
          - name: Login to Openshift
            uses: redhat-actions/oc-login@v1
            with:
              openshift_server_url: ${{ secrets.OPENSHIFT_URL }}
              openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}





            
